### ISSUE TITLE
Problem joining a server world fabric

### ISSUE THREAD

**Issue by Han3422** [TechnoVisionDev/Alchemistry#2]
Hello I cant join the server world because alchemistry is having some issues.

Used mods:
-Alchemistry-1.19.2-1.0.1
-ChemLib-1.19.2-1.0.1
-fabric-api-0.59.0+1.19.2

latest log
https://gist.github.com/Han3422/0f97f94652d198681f70e4ef42da2bed

**Comment by TechnoVisionDev** [comment]
Fixing right now, should have a hotfix out in a few minutes

**Comment by TechnoVisionDev** [comment]
Fixed in latest update on curseforge: https://www.curseforge.com/minecraft/mc-mods/alchemistry-fabric/files/3929231
Thank you for your patience! Alchemistry should be stable for multiplayer use now.

**Comment by Han3422** [comment]
Thanks!
